### ISSUE TITLE
Subcommittee Join Request for Oreste Bernardi

### ISSUE THREAD

**Issue by pellico** [rustfoundation/safety-critical-rust-consortium#103]
### Are you already a member of the Safety Critical Rust Consortium?

Yes

### What is your name?

Oreste Bernardi

### What subcommittee would you like to join?

Tooling

### ONLY FILL THIS OUT IF YOU ARE A PRODUCER IN THE CONSORTIUM. IF YOU ARE AN OBSERVER, YOU WILL BE AN OBSERVER IN THE SUBCOMMITTEE BY DEFAULT.. Do you plan to be a producer or observer in this subcommittee?

Producer

**Comment by JoelMarcey** [comment]
Triaged to @alexandruradovici
