### ISSUE TITLE
Subcommittee Join Request for Alexandru Radovici

### ISSUE THREAD

**Issue by alexandruradovici** [rustfoundation/safety-critical-rust-consortium#106]
### Are you already a member of the Safety Critical Rust Consortium?

Yes

### What is your name?

Alexandru Radovici

### What subcommittee would you like to join?

Coding Guidelines

### ONLY FILL THIS OUT IF YOU ARE A PRODUCER IN THE CONSORTIUM. IF YOU ARE AN OBSERVER, YOU WILL BE AN OBSERVER IN THE SUBCOMMITTEE BY DEFAULT.. Do you plan to be a producer or observer in this subcommittee?

Producer

**Comment by JoelMarcey** [comment]
Triaged to @PLeVasseur
