### ISSUE TITLE
Subcommittee Join Request for Enow Scott

### ISSUE THREAD

**Issue by Blindspot22** [rustfoundation/safety-critical-rust-consortium#116]
### Are you already a member of the Safety Critical Rust Consortium?

Yes

### What is your name?

Enow Scott

### What subcommittee would you like to join?

Coding Guidelines

### ONLY FILL THIS OUT IF YOU ARE A PRODUCER IN THE CONSORTIUM. IF YOU ARE AN OBSERVER, YOU WILL BE AN OBSERVER IN THE SUBCOMMITTEE BY DEFAULT.. Do you plan to be a producer or observer in this subcommittee?

Producer

**Comment by JoelMarcey** [comment]
Triaged to @PLeVasseur

**Comment by Blindspot22** [comment]
Hello @JoelMarcey :wave: 
There have just been a small modification on this issue under the question `Are you already a member of the Safety Critical Rust Consortium?`. Just wanted you to be aware of that.
