### ISSUE TITLE
Application to become a Safety Critical Rust Consortium Member

### ISSUE THREAD

**Issue by ccpalmer** [rustfoundation/safety-critical-rust-consortium#70]
### What is your name?

Charles C Palmer

### What is your preferred email address?

ccpalmer@acm.org

### Do you represent a company, institution, consortium, yourself or other entity?

Institution (Academic, etc.)

### If you represent a company, institution, consortium, or other entity, please enter it here.

Dartmouth College

### Why are you interested in joining the Safety Critical Rust Consortium?

Teach Rust and reliable and secure systems development

### Do you plan to be a producer or observer in the consortium?

Observer

**Comment by JoelMarcey** [comment]
@ccpalmer Hi. You had already filled this out https://github.com/rustfoundation/safety-critical-rust-consortium/issues/17, but you gave me a different email address. Do you want me to use your acm one instead?

**Comment by ccpalmer** [comment]
Yes please, and the “observer” flavor as well.

From: Joel Marcey ***@***.***>
Date: Thursday, November 7, 2024 at 14:43
To: rustfoundation/safety-critical-rust-consortium ***@***.***>
Cc: Charles C. Palmer ***@***.***>, Mention ***@***.***>
Subject: Re: [rustfoundation/safety-critical-rust-consortium] Application to become a Safety Critical Rust Consortium Member (Issue #70)

@ccpalmer<https://github.com/ccpalmer> Hi. You had already filled this out #17<https://github.com/rustfoundation/safety-critical-rust-consortium/issues/17>, but you gave me a different email address. Do you want me to use your acm one instead?

**Comment by JoelMarcey** [comment]
Done.
