### ISSUE TITLE
Subcommittee Join Request for Douglas Deslauriers

### ISSUE THREAD

**Issue by vapdrs** [rustfoundation/safety-critical-rust-consortium#99]
### Are you already a member of the Safety Critical Rust Consortium?

Yes

### What is your name?

Douglas Deslauriers

### What subcommittee would you like to join?

Coding Guidelines

### ONLY FILL THIS OUT IF YOU ARE A PRODUCER IN THE CONSORTIUM. IF YOU ARE AN OBSERVER, YOU WILL BE AN OBSERVER IN THE SUBCOMMITTEE BY DEFAULT.. Do you plan to be a producer or observer in this subcommittee?

Producer

**Comment by JoelMarcey** [comment]
Triage to @PLeVasseur
